language: php

# list any PHP version you want to test against
php:
  - 5.6
  - 7.0
  - hhvm

before_script:
     # Composer install and update;
     - composer self-update
     - composer update

script: phpunit --configuration phpunit.xml.dist --coverage-text
